<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <AssemblyName>StaticArtifactLab</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\StaticArtifactLab.Core\StaticArtifactLab.Core.csproj" />
  </ItemGroup>
</Project>

