<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <AssemblyName>static-artifact</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\StaticArtifactLab.Core\StaticArtifactLab.Core.csproj" />
  </ItemGroup>
</Project>

